# Generated by Django 2.1.1 on 2019-08-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20190806_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='blogging.Category'),
        ),
    ]
