# Generated by Django 2.1.1 on 2019-08-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_auto_20190811_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='blogging.Category'),
        ),
    ]
